events { worker_connections 1024; }

http {
    upstream catalog_servers {
        server catalog-1:8001;
        server catalog-2:8002;
    }

    server {
        listen 80;

        location /auth/ {
            rewrite ^/auth/(.*) /$1 break;
            proxy_pass http://auth:8000;
            proxy_set_header Host $host;
        }

        location /catalog/ {
            rewrite ^/catalog/(.*) /$1 break;
            proxy_pass http://catalog_servers;
            proxy_set_header Host $host;
        }
    }
}
